### PR TITLE
converting github url to raw url - still works for raw url #240

### LINKED ISSUE #240: Azure devops generator is able to construct a github raw url
When creating a new azure devops project from an existing Azure DevOps template, we pass the github raw URL or a zip file. However when a users selects the github zip file the browser does not give the github raw URL. The users has to construct it or we need to provide the link.

Ask: Azure DevOps generator is able to construct the github raw url given a zip file url.

Steps to reproduce the issue.

Sign in to Azure DevOps Generator

Create a new project, ex: “Template_001” then select your organization “.

Click “Choose template”, select Github. Past the raw url: 
https://raw.githubusercontent.com/microsoft/azuredevopsgenerator/master/azuresentinel/AzureSentinel.zip

Click “Submit” then “Create Project”

An Azure DevOps project will be created in your organization

### PR DESCRIPTION
**Pull request by aksh-h**
Based on user suggestion, accepting GitHub zip file link instead of raw URL

Closes #240

### CODE REVIEW

File: src/VstsDemoBuilder/Controllers/EnvironmentController.cs [hunk 1]
```diff
@@ -131,7 +131,7 @@ public JsonResult GetGroups()
                     _templates.Groups = new List<string>();
                     foreach (var group in templates.Groups)
                     {
-                        if (group.ToLower() != "private")
+                        //if (group.ToLower() != "private")
```
Comment (dmckinstry) [inline src/VstsDemoBuilder/Controllers/EnvironmentController.cs:134]: If you don't need the "private" then you should probably clean up this code

Comment (aksh-h) [reply src/VstsDemoBuilder/Controllers/EnvironmentController.cs:134]: I was testing something, forgot to remove this. I'll clean up.
